server:
   port: 8080
   servlet:
      context-path: /taotao

spring:
    datasource:
        name: test
       # 如果不加入?useUnicode=true&characterEncoding=UTF-8，那么插入中文的时候会乱码
        url: jdbc:mysql://localhost:3306/taotao?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

    # Freemarker 配置
    freemarker:
        template-loader-path: classpath:/templates/
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl

    resources:
        staticLocations: classpath:/static/

#Mybatis
mybatis:
   #   config-locations: classpath:mybatis/mybatis-config.xml
   mapper-locations: classpath:mapper/*Mapper.xml
   #  给pojo定义别名
   type-aliases-package: com.taota.pojo


# 打印mybatis的SQL语句
logging:
  level:
     # com.taotao.mapper 是mapper接扣的包名
      com.taotao.mapper: DEBUG


# 分页配置
pagehelper:
   helperDialect: mysql
   # 禁用参数合理化功能，避免当传入页数小于1或者大于最大值时候返回不为空而是返回默认的数据
   reasonable: false

# 自定义上传文件的路径
uploadImage:
    location: /Users/luoshixin/Desktop/workspace/taotao/taotao-manager/taotao-manager-web/src/main/resources/static/tem

