server:
   port: 8083
   servlet:
      context-path: /taotao/es/

#Mybatis
mybatis:
   #   config-locations: classpath:mybatis/mybatis-config.xml
   mapper-locations: classpath:mapper/*Mapper.xml
   #  给pojo定义别名
   type-aliases-package: com.taota.pojo

# 打印mybatis的SQL语句
logging:
  level:
     # com.taotao.mapper 是mapper接扣的包名
      com.taotao.mapper: DEBUG



spring:
    datasource:
        name: test
       # 如果不加入?useUnicode=true&characterEncoding=UTF-8，那么插入中文的时候会乱码
        url: jdbc:mysql://localhost:3306/taotao?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: lsx1991913
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

    data:
        elasticsearch:
              cluster-nodes: 103.200.97.224:9200